apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gestion-rrhh.fullname" . }}-db-secret
type: Opaque
stringData:
  username: {{ .Values.dbCredentials.username }}
  password: {{ .Values.dbCredentials.password }}
